---
apiVersion: v1
data:
  broker.conf: |-
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=0
    brokerIP1 =broker-a-link
    namesrvAddr=mq-ns.prod-eft-link.svc.cluster.local:9876
    brokerEnableProxy=true
    brokerWeight=100
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    autoCreateSubscriptionGroup=true
    waitTimeMillsInSendQueue=5000
    registerNameServerPeriod=5000
    listenPort=10911
    deleteWhen=04
    fileReservedTime=120
    dynamicTopicEnabled=true
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=300000
    destroyMapedFileInterval=120000
    redeleteHangedFileInterval=120000
    diskMaxUsedSpaceRatio=88
    maxMessageSize=4194304
    flushCommitLogLeastPages=4
    flushConsumeQueueLeastPages=2
    flushCommitLogThoroughInterval=10000
    flushConsumeQueueThoroughInterval=60000
    checkTransactionMessageEnable=false
    sendMessageThreadPoolNums=16
    pullMessageThreadPoolNums=16
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: broker-a